name: Deploy to github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Setup Node.js environment
        uses: actions/setup-node@v2.1.5
      - run: npm install
      - run: npm run build-examples
      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: build
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}
      - run: |
          curl -XPOST -u "${{ secrets.PA_USERNAME}}:${{secrets.PA_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/Ashwin-RXP/demoproj/dispatches --data '{"event_type": "build_application"}'
      - name: Send Teams Notification
        if: success()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: ${{ github.event.head_commit.message }}
          summary: Design Ops new Release deployed
          text: Commit Url ${{ github.event.head_commit.url }}
