name: Deploy to github pages

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3.0.2
        with:
          persist-credentials: false

      - name: Setup Node.js environment
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install dependencies
        run: npm install

      - name: Run unit tests
        run: npm run test

      - name: Build Storybook 🔧
        run: npm run build-storybook

      - name: Deploy
        uses: crazy-max/ghaction-github-pages@v2.3.0
        with:
          build_dir: docs-build
        env:
          GITHUB_TOKEN: ${{ secrets.PA_TOKEN }}

      - run: |
          curl -XPOST -u "${{ secrets.PA_USERNAME}}:${{secrets.PA_TOKEN}}" -H "Accept: application/vnd.github.everest-preview+json" -H "Content-Type: application/json" https://api.github.com/repos/RXPServices/demoproj/dispatches --data '{"event_type": "build_application"}'

      - name: Send Teams Notification
        if: success()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: ''
          summary: 'GitHub Actions Message'
          text: ''
          theme_color: ''
          sections: '[{ "activityImage": "https://www.capgemini.com/au-en/wp-content/themes/capgemini-komposite/assets/images/logo.svg", "activityTitle": "GitHub Action invoked",  "activitySubtitle": "Event triggered by ${{ github.event.head_commit.author.name }}", "activityText": "Commit message: [${{ github.event.head_commit.message}}](${{ github.event.head_commit.url }})" }]'
          actions: '[{ "@type": "OpenUri", "name": "View Commit", "targets": [{ "os": "default", "uri": "${{ github.event.head_commit.url }}" }] }]'         
