name: Create pull request

on:
  push:
    branches-ignore: main

jobs:
  action-pull-request:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create pull request
        uses: devops-infra/action-pull-request@v0.5.0
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          title: ${{ github.event.commits[0].message }}
          target_branch: main
          assignee: ${{ github.actor }}
          reviewer: 'angyaos'
          template: .github/pull_request_template.md

      - name: Send Teams Notification
        if: success()
        uses: aliencube/microsoft-teams-actions@v0.8.0
        with:
          webhook_uri: ${{ secrets.TEAMS_WEBHOOK }}
          title: ${{ github.event.head_commit.message }} - ${{github.event.head_commit.author.name }}
          summary: Design Ops new Release deployed
          text: Commit Url ${{ github.event.head_commit.url }}
